[package]
name = "rustyboy-web"
version = "0.1.0"
authors = ["Félix Léveillé <flxleveille@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.24"
serde = { version = "1.0.94", features = ["derive"] }
rustyboy-core = { path = "../core" }

[dependencies.web-sys]
version = "0.3.24"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlTexture',
  'Window',
]

[dependencies.wasm-bindgen]
version = "0.2.47"
features = ["serde-serialize"]