[package]
name = "rustyboy-web"
version = "0.1.0"
authors = ["Félix Léveillé <flxleveille@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.45"
wasm-bindgen-futures = "0.3.22"
js-sys = "0.3.22"
rustyboy-core = { path = "../core" }
futures = "0.1.27"

[dependencies.web-sys]
version = "0.3.22"
features = [
  'ImageBitmap',
  'ImageData',
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
]