version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Build
          command: |
            make build -s

      - run:
          name: Check lint
          command: |
            make lint -s

      - run:
          name: Check tests
          command: |
            make test -s
