version: 2
jobs:
  build:
    docker:
      - image: flix477/rustyboy:latest
    steps:
      - checkout
      - run: make check -s
  lint:
    docker:
      - image: flix477/rustyboy:latest
    steps:
      - checkout
      - run: make lint -s
  test:
    docker:
      - image: flix477/rustyboy:latest
    steps:
      - checkout
      - run: make test -s
workflows:
  version: 2
  check:
    jobs:
      - build
      - lint
      - test
