version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            cd src/core
            cargo fmt --all -- --check
            cd ../pc
            cargo fmt --all -- --check

      - run:
          name: Build
          command: |
            cd src/core
            cargo build
            cd ../pc
            cargo build

      - run:
          name: Check tests
          command: |
            cd src/core
            cargo test
            cd ../pc
            cargo test
