version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            ./run-on-modified.sh "cargo fmt --all -- --check"

      - run:
          name: Check lint
          command: |
            rustup component add clippy
            ./run-on-modified.sh "cargo clippy --all --all-targets -- -Dwarnings -Drust-2018-idioms"

      - run:
          name: Build
          command: |
            ./run-on-modified.sh "cargo build"

      - run:
          name: Check tests
          command: |
            ./run-on-modified.sh "cargo test"
