version: 2
jobs:
  build:
    docker:
      - image: flix477/rustyboy:latest

    steps:
      - checkout

      - run:
          name: Check
          command: |
            make check -s

      - run:
          name: Check lint
          command: |
            make lint -s

      - run:
          name: Check tests
          command: |
            make test -s
